# Configuración de Cloudflare Pages para TechNovaStore Frontend

name = "technovastore-frontend"
compatibility_date = "2024-01-01"

# Configuración de Pages
pages_build_output_dir = ".next"

[build]
command = "npm run build:pages"
cwd = ""

[build.upload]
format = "service-worker"

# Variables de entorno para producción
[env.production]
NEXT_PUBLIC_API_URL = "https://api.technovastore.com"
NEXT_PUBLIC_CHATBOT_URL = "https://chatbot.technovastore.com"
NEXT_PUBLIC_SOCKET_URL = "https://chatbot.technovastore.com"
NEXT_PUBLIC_APP_URL = "https://technovastore.com"

# Variables de entorno para preview
[env.preview]
NEXT_PUBLIC_API_URL = "https://api-preview.technovastore.com"
NEXT_PUBLIC_CHATBOT_URL = "https://chatbot-preview.technovastore.com"
NEXT_PUBLIC_SOCKET_URL = "https://chatbot-preview.technovastore.com"
NEXT_PUBLIC_APP_URL = "https://preview.technovastore.com"
