groups:
  - name: technovastore_alerts
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.job }}"

      # Performance Alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.job }}"

      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.job }}"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is {{ $value }}MB on {{ $labels.job }}"

      # Database Alerts
      - alert: MongoDBConnectionsHigh
        expr: mongodb_connections{state="current"} > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "MongoDB connections are high"
          description: "MongoDB has {{ $value }} active connections"

      - alert: PostgreSQLConnectionsHigh
        expr: pg_stat_database_numbackends > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL connections are high"
          description: "PostgreSQL has {{ $value }} active connections"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is {{ $value }}%"

      # Business Logic Alerts
      - alert: OrderProcessingDelay
        expr: increase(orders_processing_time_seconds_sum[10m]) / increase(orders_processing_time_seconds_count[10m]) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Order processing is slow"
          description: "Average order processing time is {{ $value }}s"

      - alert: SyncEngineFailures
        expr: increase(sync_engine_failures_total[10m]) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Sync engine has multiple failures"
          description: "Sync engine has {{ $value }} failures in the last 10 minutes"

      - alert: AutoPurchaseFailures
        expr: increase(auto_purchase_failures_total[10m]) > 3
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Auto purchase system has failures"
          description: "Auto purchase has {{ $value }} failures in the last 10 minutes"