global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Core Services
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'ticket-service'
    static_configs:
      - targets: ['ticket-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Automation Services
  - job_name: 'sync-engine'
    static_configs:
      - targets: ['sync-engine:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'auto-purchase'
    static_configs:
      - targets: ['auto-purchase:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'shipment-tracker'
    static_configs:
      - targets: ['shipment-tracker:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # AI Services
  - job_name: 'chatbot'
    static_configs:
      - targets: ['chatbot:3001']
    metrics_path: '/metrics'
    scrape_interval: 20s

  - job_name: 'recommender'
    static_configs:
      - targets: ['recommender:3000']
    metrics_path: '/metrics'
    scrape_interval: 20s

  # Infrastructure Services
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Frontend (Next.js)
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s